#!/usr/bin/env bash
# -*- coding: utf-8 -*-

$(git --version)
if [ $? -ne 0 ]
then
	echo "Git has not been installed!"
	exit 1;
fi

cat > ~/.gitconfig <<EOF

[user]
    name = wangzhizhou
    email = 824219521@qq.com

[diff]
    submodule = log

[alias]

    l = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative --decorate --simplify-by-decoration --all
  
    b = branch
    bv = branch -vv

    pl = pull
    pu = push
    po = push origin

    a = add
    c = commit
    co = checkout
    cl = clone
    cdf = clean -dxf
    clrs = clone --recurse-submodules

    d = diff
    dsm = diff --submodule

    m = merge
    
    s = status
    st = stash
    sl = stash list
    sp = stash pop


    sm = submodule
    smi = submodule init
    smu = submodule update
    smur = submodule update --remote

    r = remote
    rv = remote -v

    rst = reset
    rvt = revert

    h = config --global --list
[color]
    ui = auto

EOF
