#!/usr/bin/env bash

function usage()
{
    echo
    echo "Usage:"
    echo
    echo "    joker [ -j <jdk-tar.gz-package-url> | -v | -s ]"
    echo
    echo "Options:"
    echo
    echo "    -g, config the git user.name, user.email and alias"
    echo
    echo "    -j <jdk-tar.gz-package-url>, install specified jdk version"
    echo 
    echo "    -v, config the user vim schema"
    echo
    echo "    -s, config the user shell schema"
    echo
    echo "    -t, install tools with apt-get"
}

if [ $# -eq 0 ]
then
    usage
    exit 1
fi

kernel=$(uname -s)

case "$kernel" in 
    Darwin)
        echo Darwin kernel;;

    Linux)
        echo Linux kernel;;

    *)
        echo "Unknown kernel"
        exit 1;;
esac

while getopts ":gjvst" opt
do
    case "$opt" in
    g)
        source ./git/git-config
        ;;
    j)
        source ./java/install-jdk
        ;;
    v)
        source ./vim/vim-config
        ;;
    s)
        source ./shell/bash-config
        ;;
    t)  apt-get update && apt-get install -y git curl nginx screen
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

echo Completed!