#!/usr/bin/env bash

function usage()
{
    echo
    echo "Usage:"
    echo
    echo "    joker [ -j <jdk-tar.gz-package-url> | -v | -s ]"
    echo
    echo "Options:"
    echo
    echo "    -j <jdk-tar.gz-package-url>, install specified jdk version"
    echo 
    echo "    -v, config the user vim schema"
    echo
    echo "    -s, config the user shell schema"
    echo
}

if [ $# -eq 0 ]
then
    usage
    exit 1
fi

kernel=$(uname -s)

case "$kernel" in 
    Darwin)
        echo Darwin kernel;;

    Linux)
        echo Linux kernel;;

    *)
        echo "Unknown kernel"
        exit 1;;
esac

while getopts ":jvs" opt
do
    case "$opt" in
    j)
        source install-jdk
        ;;
    v)
        source vim-config
        ;;
    s)
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done