#!/usr/bin/env bash

function usage()
{
    echo Usage:
}

if [ $# -eq 0 ]
then
    usage
    exit 1
fi

kernel=$(uname -s)

case "$kernel" in 
    Darwin)
        echo Darwin kernel;;

    Linux)
        echo Linux kernel;;

    *)
        echo "Unknown kernel"
        exit 1;;
esac

while getopts ":vs" opt
do
    case "$opt" in
    v)
        source vim-config
        ;;
    s)
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done