#!/usr/bin/env bash
# EasyWork — Shell Completion Library
# Provides: shell completion generation, injection, and removal.
# Sourced by bin/easywork after common.sh.

# ─── Shell Completion Setup ─────────────────────────────────────

# Detect the primary shell rc file for the current shell
_detect_rc_file() {
    if declare -f _detect_shell_rc > /dev/null 2>&1; then
        _detect_shell_rc
        return
    fi
    local os_type sh_type
    os_type="$(detect_os)"
    sh_type="$(detect_shell)"
    if [[ "$sh_type" == "zsh" ]]; then
        echo "$HOME/.zshrc"
        return
    fi
    case "$os_type" in
        macos)
            case "$sh_type" in
                bash) echo "$HOME/.bash_profile" ;;
                *) echo "$HOME/.bashrc" ;;
            esac
            ;;
        *) echo "$HOME/.bashrc" ;;
    esac
}

# Detect all shell rc files that should receive completion source lines
# Format: "shell_type:absolute_path" (one per line)
_detect_completion_rc_files() {
    local os_type
    os_type="$(detect_os)"
    local files=()

    # zsh always uses .zshrc
    files+=("zsh:$HOME/.zshrc")

    # bash: platform-specific primary rc
    if [[ "$os_type" == "macos" ]]; then
        files+=("bash:$HOME/.bash_profile")
        [[ -f "$HOME/.bashrc" ]] && files+=("bash:$HOME/.bashrc")
    else
        files+=("bash:$HOME/.bashrc")
        [[ -f "$HOME/.bash_profile" ]] && files+=("bash:$HOME/.bash_profile")
    fi

    printf '%s\n' "${files[@]}"
}

_setup_completions() {
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY-RUN] 将配置 shell 补全"
        return 0
    fi

    local comp_dir="$HOME/.easywork/completions"
    mkdir -p "$comp_dir"

    # Build dynamic command list: built-in + registered modules
    local mod_list
    mod_list="$(list_modules_sorted 2> /dev/null | tr '\n' ' ' || true)"

    # ── Bash completion — context-aware: flags, subcommands, module names ──
    cat > "$comp_dir/easywork.bash" << BASH_COMP
# EasyWork bash completion — generated by easywork ${EASYWORK_VERSION}
# DO NOT EDIT — regenerated on 'easywork install'

_easywork() {
    COMPREPLY=()
    local cur
    cur="\${COMP_WORDS[COMP_CWORD]}"

    local global_opts="--yes -y --dry-run --verbose -v"
    local uninstall_opts="--keep-config --remove-config"
    local commands="install uninstall config version update help completion"
    local modules="${mod_list}"

    local cmd=""
    local i
    for ((i = 1; i < COMP_CWORD; i++)); do
        [[ "\${COMP_WORDS[i]}" != -* ]] && { cmd="\${COMP_WORDS[i]}"; break; }
    done

    if [[ "\$cur" == -* ]]; then
        local opts="\$global_opts"
        [[ "\$cmd" == "uninstall" ]] && opts="\$opts \$uninstall_opts"
        COMPREPLY=(\$(compgen -W "\$opts" -- "\$cur"))
        return
    fi

    if [[ -z "\$cmd" ]]; then
        COMPREPLY=(\$(compgen -W "\$commands \$modules" -- "\$cur"))
        return
    fi

    case "\$cmd" in
        install | uninstall) COMPREPLY=(\$(compgen -W "\$modules" -- "\$cur")) ;;
        config)              COMPREPLY=(\$(compgen -W "edit show" -- "\$cur")) ;;
    esac
}
complete -F _easywork easywork
BASH_COMP

    # ── Zsh completion — explicit compdef registration (sourced directly) ──
    cat > "$comp_dir/_easywork" << ZSH_COMP
#compdef easywork
# EasyWork zsh completion — generated by easywork ${EASYWORK_VERSION}
# DO NOT EDIT — regenerated on 'easywork install'

_easywork() {
    local -a cmds modules
    cmds=(install uninstall config version update help completion)
    modules=(${mod_list})

    _arguments -C \\
        '--yes[跳过交互确认]' \\
        '-y[跳过交互确认]' \\
        '--dry-run[预览变更不执行]' \\
        '--verbose[详细输出]' \\
        '-v[详细输出]' \\
        '--keep-config[卸载时保留配置文件]' \\
        '--remove-config[卸载时删除配置文件]' \\
        "1:命令:(\$cmds \$modules)" \\
        '*::参数:->args'

    case "\$state" in
        args)
            case "\${line[1]}" in
                install | uninstall) compadd \$modules ;;
                config)              compadd edit show ;;
            esac
            ;;
    esac
}

# Register explicitly — this file is sourced directly, not autoloaded via fpath
if typeset -f compdef > /dev/null 2>&1; then
    compdef _easywork easywork
fi
ZSH_COMP

    # Inject source lines into all detected shell rc files
    local injected_any=false
    local sh_type rc_file source_line
    while IFS=: read -r sh_type rc_file; do
        [[ -f "$rc_file" ]] || touch "$rc_file"

        if [[ "$sh_type" == "zsh" ]]; then
            source_line="source $comp_dir/_easywork  # EasyWork completion"
        else
            source_line="source $comp_dir/easywork.bash  # EasyWork completion"
        fi

        if ! grep -qF "# EasyWork completion" "$rc_file" 2> /dev/null; then
            printf '\n%s\n' "$source_line" >> "$rc_file"
            injected_any=true
            log_info "Shell 补全已注入: ${rc_file}"
        fi
    done < <(_detect_completion_rc_files)

    if $injected_any; then
        log_success "Shell 补全已配置（重启 shell 或运行 source 后生效）"
    fi
}

_remove_completions() {
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY-RUN] 将移除 shell 补全配置"
        return 0
    fi

    local comp_dir="$HOME/.easywork/completions"
    local sh_type rc_file tmpfile

    # Remove completion source lines from all detected rc files
    while IFS=: read -r sh_type rc_file; do
        if [[ -f "$rc_file" ]]; then
            tmpfile="${rc_file}.tmp.$$"
            grep -vF "# EasyWork completion" "$rc_file" > "$tmpfile" 2> /dev/null || true
            mv "$tmpfile" "$rc_file"
            log_info "已从 ${rc_file} 移除补全配置"
        fi
    done < <(_detect_completion_rc_files)

    rm -f "$comp_dir/easywork.bash" "$comp_dir/_easywork"
    rmdir "$comp_dir" 2> /dev/null || true
}

# ─── CLI: Completion Command ─────────────────────────────────
cmd_completion() {
    local sub="${1:-setup}"
    case "$sub" in
        setup | install)
            _discover_modules "$LIB_DIR"
            _setup_completions
            ;;
        remove | uninstall | clean)
            _remove_completions
            log_success "Shell 补全已移除"
            ;;
        status | show)
            local comp_dir="$HOME/.easywork/completions"
            echo "补全文件目录: ${comp_dir}"
            echo ""
            if [[ -f "$comp_dir/easywork.bash" ]]; then
                echo "  bash: ${comp_dir}/easywork.bash ✓"
            else
                echo "  bash: (未安装)"
            fi
            if [[ -f "$comp_dir/_easywork" ]]; then
                echo "  zsh:  ${comp_dir}/_easywork ✓"
            else
                echo "  zsh:  (未安装)"
            fi
            echo ""
            echo "已注入的 shell 配置文件:"
            local found_any=false
            local sh_type rc_file
            while IFS=: read -r sh_type rc_file; do
                if [[ -f "$rc_file" ]] && grep -qF "# EasyWork completion" "$rc_file" 2> /dev/null; then
                    echo "  ${sh_type}: ${rc_file} ✓"
                    found_any=true
                fi
            done < <(_detect_completion_rc_files)
            if ! $found_any; then
                echo "  (无 — 运行 easywork completion setup 安装补全)"
            fi
            ;;
        *)
            echo "用法: easywork completion <子命令>"
            echo ""
            echo "子命令:"
            echo "  setup    生成并注入补全到 shell 配置文件"
            echo "  remove   从 shell 配置文件移除补全"
            echo "  status   查看补全安装状态"
            exit $EXIT_ERROR
            ;;
    esac
}
